# -*- coding: utf-8 -*-
"""
Build Fig.4/Fig.5 overlay NetCDF files from the wind spacetime products NetCDF.

Input:
    wind_spacetime_products_europe_main_admin_no_russia_no_iceland.nc

Outputs:
    overlay_result_long_term_background.nc
    overlay_result_same_month_background.nc

The Fig.4 preparation script expects each overlay NetCDF to contain:
    z_value    = standardized anomaly intensity
    freq_value = anomaly frequency

This script derives those variables from the products NetCDF generated by:
    01_build_wind_spacetime_products_from_ERA5.py
"""

from pathlib import Path
import os
import xarray as xr


BASE = Path(os.environ.get("ORIGINAL_BASE", r"E:\RF B+G"))

PRODUCTS_NC = Path(os.environ.get(
    "WIND_PRODUCTS_NC",
    str(BASE / r"wind_spacetime_maps_europe_main_admin"
               r"\wind_spacetime_products_europe_main_admin_no_russia_no_iceland.nc")
))

OUTDIR = Path(os.environ.get("WIND_OVERLAY_OUTDIR", str(BASE / "windmap")))
OUTDIR.mkdir(parents=True, exist_ok=True)

OUT_LONG = Path(os.environ.get(
    "WIND_OVERLAY_LONG_NC",
    str(OUTDIR / "overlay_result_long_term_background.nc")
))

OUT_MONTH = Path(os.environ.get(
    "WIND_OVERLAY_MONTH_NC",
    str(OUTDIR / "overlay_result_same_month_background.nc")
))


def open_dataset_fallback(path: Path):
    errors = []
    for engine in ["h5netcdf", "scipy", "netcdf4", None]:
        try:
            if engine is None:
                print(f"Opening NetCDF with xarray default: {path}")
                return xr.open_dataset(path)
            print(f"Opening NetCDF with engine={engine}: {path}")
            return xr.open_dataset(path, engine=engine)
        except Exception as e:
            errors.append(f"{engine or 'default'}: {repr(e)}")
    raise RuntimeError("Could not open NetCDF with available engines:\n" + "\n".join(errors))


def require_vars(ds, vars_needed):
    missing = [v for v in vars_needed if v not in ds.data_vars]
    if missing:
        raise KeyError(
            f"Missing variable(s) {missing} in {PRODUCTS_NC}\n"
            f"Available variables: {list(ds.data_vars)}"
        )


def write_overlay(ds, z_var: str, freq_var: str, out_path: Path):
    require_vars(ds, [z_var, freq_var])
    out = xr.Dataset(
        {
            "z_value": ds[z_var].astype("float32"),
            "freq_value": ds[freq_var].astype("float32"),
        }
    )
    # Preserve useful coordinate metadata and compress.
    encoding = {
        "z_value": {"zlib": True, "complevel": 4, "dtype": "float32"},
        "freq_value": {"zlib": True, "complevel": 4, "dtype": "float32"},
    }
    out.to_netcdf(out_path, encoding=encoding)
    print(f"Saved overlay NetCDF: {out_path}")


def main():
    if not PRODUCTS_NC.exists():
        raise FileNotFoundError(f"WIND_PRODUCTS_NC not found: {PRODUCTS_NC}")

    ds = open_dataset_fallback(PRODUCTS_NC)

    # Long-term background: standardized relative to the local long-term distribution.
    # Frequency is annualized to match the map/regime interpretation.
    write_overlay(
        ds,
        z_var="max_z_long",
        freq_var="freq_long_per_year",
        out_path=OUT_LONG,
    )

    # Same-month background: standardized relative to the local same-calendar-month distribution.
    write_overlay(
        ds,
        z_var="max_z_month",
        freq_var="freq_month_per_year",
        out_path=OUT_MONTH,
    )


if __name__ == "__main__":
    main()
